package mingu.spring.clean.utils;

public enum MessageCode {
    // ADMIN
    ADMIN_EXCEPTION_NOT_FOUND,

    // USER
    USER_EXCEPTION_NOT_FOUND,
    USER_VALID_EMAIL,
    USER_VALID_NAME,

    // RENTAL
    RENTAL_EXCEPTION_NOT_FOUND,

    // CUSTOMER
    CUSTOMER_EXCEPTION_NOT_FOUND,

    // RENTAL COMPANY
    RENTAL_COMPANY_EXCEPTION_NOT_FOUND,
}
