spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        discriminator:
          ignore_explicit_for_joined: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  messages:
    fallback-to-system-locale: false # messages.properties 에서 기본값을 가져옴 (헤더가 없다면 디폴트 언어)

server:
  error:
    include-stacktrace: never
  port: 8080