spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        discriminator:
          ignore_explicit_for_joined: true

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  error:
    include-stacktrace: never
  port: 8080